### ISSUE TITLE
download sample

### ISSUE THREAD

**Issue by azfayel** [diogo-fern/malsub#3]
when i used the d parameter to fetch files from vendors (Openphish, malshare, or phishtank), i have a list of link but not the samples.

**Comment by diogo-fernan** [comment]
Files are downloaded to `downl/`. Have you checked that folder?

**Comment by azfayel** [comment]
Hello Yes, but it contains a list of url Not the sample. Richard Le 3 avr. 2017 8:41 PM, Diogo Fernandes <notifications@github.com> a écrit :Files are downloaded to downl/. Have you checked that folder?

**Comment by diogo-fernan** [comment]
OpenPhish and PhishTank are not repositories of malware samples. These contain lists of malicious URLs updated in real-time, which are downloaded by malsub.

On the other hand, malshare is indeed a malware repository and should be working just fine.
Are you having issues with malshare? If so, please provide some details.

**Comment by diogo-fernan** [comment]
@azfayel is the issue still occurring for you?

**Comment by azfayel** [comment]
Hello Diego I tried to download several hashes but not found in ms data base. Richard Le 14 avr. 2017 12:37 PM, Diogo Fernandes <notifications@github.com> a écrit :@azfayel is the issue still occurring for you?

**Comment by diogo-fernan** [comment]
Ok. Everything seems to be working correctly.
